#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <neuro_app_icons.h>

int32_t neuro_app_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm neuro_app!");

    return 0;
}
